https://opendata.adsb.fi/api/v3/lat/48.8530/lon/2.3499/dist/14
{"ac":[
{"hex":"39bca0","type":"adsb_icao","r":"F-HPFA","t":"HR20","desc":"ROBIN HR-200","alt_baro":"ground","gs":11.8,"track":126.56,"category":"A1","lat":48.810382,"lon":2.069694,"nic":8,"rc":75,"seen_pos":20.618,"version":0,"nac_p":8,"sil":2,"sil_type":"perhour","mlat":[],"tisb":[],"messages":16214,"seen":20.6,"rssi":-30.8,"dst":11.343,"dir":257.1},
{"hex":"398322","type":"mlat","flight":"FHAZC   ","r":"F-HAZC","t":"SIRA","desc":"TECNAM P-2002 Sierra","alt_baro":600,"calc_track":92,"baro_rate":0,"squawk":"7000","lat":48.824203,"lon":2.093922,"nic":0,"rc":0,"seen_pos":32.416,"alert":0,"spi":0,"mlat":["baro_rate","lat","lon","nic","rc"],"tisb":[],"messages":4835,"seen":2.8,"rssi":-6.4,"dst":10.240,"dir":260.4},
{"hex":"39c475","type":"adsb_icao","flight":"FHRDV   ","r":"F-HRDV","t":"BR23","desc":"BRM AERO Bristell B23","alt_baro":800,"alt_geom":1325,"gs":77.1,"ias":72,"tas":72,"mach":0.108,"wd":283,"ws":7,"track":76.50,"roll":-1.93,"mag_heading":69.79,"true_heading":71.80,"baro_rate":192,"squawk":"7000","emergency":"none","category":"A1","nav_qnh":1024.8,"nav_altitude_mcp":1216,"nav_modes":[],"lat":48.730277,"lon":2.104099,"nic":9,"rc":75,"seen_pos":0.025,"version":2,"nic_baro":1,"nac_p":10,"nac_v":2,"sil":3,"sil_type":"perhour","gva":2,"sda":2,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":3993,"seen":0.0,"rssi":-20.9,"dst":12.187,"dir":232.9},
{"hex":"407535","type":"adsb_icao","flight":"BAW552F ","r":"G-TTNE","t":"A20N","desc":"AIRBUS A-320neo","alt_baro":37000,"alt_geom":38000,"gs":409.9,"ias":255,"tas":454,"mach":0.788,"wd":209,"ws":83,"oat":-55,"tat":-27,"track":146.04,"track_rate":0.00,"roll":0.00,"mag_heading":153.46,"true_heading":155.45,"baro_rate":-64,"geom_rate":-64,"squawk":"5262","emergency":"none","category":"A3","nav_qnh":1012.8,"nav_altitude_mcp":36992,"lat":48.737457,"lon":2.121277,"nic":8,"rc":186,"seen_pos":0.182,"version":2,"nic_baro":1,"nac_p":9,"nac_v":1,"sil":3,"sil_type":"perhour","gva":2,"sda":3,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":59958,"seen":0.0,"rssi":-12.4,"dst":11.386,"dir":232.6},
{"hex":"394a04","type":"adsb_icao","flight":"AFR090  ","r":"F-GSQE","t":"B77W","desc":"BOEING 777-300ER","alt_baro":7500,"alt_geom":8075,"gs":265.1,"ias":255,"mach":0.440,"track":264.81,"mag_heading":260.33,"true_heading":262.37,"baro_rate":2240,"geom_rate":2272,"squawk":"5622","emergency":"none","category":"A5","nav_qnh":1012.8,"nav_altitude_mcp":19008,"nav_heading":262.97,"lat":48.977749,"lon":2.224225,"nic":8,"rc":186,"seen_pos":0.098,"version":2,"nic_baro":1,"nac_p":9,"nac_v":1,"sil":3,"sil_type":"perhour","gva":2,"sda":2,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":2039,"seen":0.1,"rssi":-8.7,"dst":8.984,"dir":326.5},
{"hex":"06a3cf","type":"adsb_icao","flight":"QAF9    ","r":"A7-HWL","t":"A320","dbFlags":1,"desc":"AIRBUS A-320","ownOp":"Qatar Amiri Flight","alt_baro":3775,"alt_geom":4325,"gs":213.2,"ias":213,"tas":222,"mach":0.344,"wd":287,"ws":11,"track":246.80,"track_rate":0.12,"roll":0.53,"mag_heading":246.62,"true_heading":248.68,"baro_rate":320,"geom_rate":320,"squawk":"0665","emergency":"none","category":"A3","nav_qnh":1024.8,"nav_altitude_mcp":8992,"nav_heading":246.80,"lat":48.927845,"lon":2.294191,"nic":8,"rc":186,"seen_pos":0.112,"version":2,"nic_baro":1,"nac_p":9,"nac_v":1,"sil":3,"sil_type":"perhour","gva":2,"sda":3,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":1308,"seen":0.1,"rssi":-8.8,"dst":5.005,"dir":333.9},
{"hex":"3964f0","type":"adsb_icao","flight":"TVF25CB ","r":"F-GZHQ","t":"B738","desc":"BOEING 737-800","alt_baro":"ground","gs":6.2,"true_heading":19.69,"lat":48.737114,"lon":2.383540,"nic":8,"rc":186,"seen_pos":54.321,"version":2,"sil_type":"perhour","alert":0,"spi":0,"mlat":[],"tisb":[],"messages":8,"seen":54.3,"rssi":-27.1,"dst":7.091,"dir":169.2},
{"hex":"c000eb","type":"adsb_icao","flight":"WJA9    ","r":"C-FAJA","t":"B789","desc":"BOEING 787-9 Dreamliner","alt_baro":3050,"alt_geom":3575,"gs":191.8,"ias":193,"tas":198,"mach":0.308,"track":292.69,"track_rate":0.00,"roll":0.70,"mag_heading":287.93,"true_heading":290.03,"baro_rate":1952,"geom_rate":1920,"squawk":"5635","emergency":"none","category":"A5","nav_qnh":1026.4,"nav_altitude_mcp":10016,"nav_heading":322.03,"nav_modes":["autopilot","vnav","lnav","tcas"],"lat":49.019348,"lon":2.423119,"nic":8,"rc":186,"seen_pos":0.223,"version":2,"nic_baro":1,"nac_p":9,"nac_v":1,"sil":3,"sil_type":"perhour","gva":2,"sda":2,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":254,"seen":0.2,"rssi":-13.0,"dst":10.406,"dir":16.1},
{"hex":"e80471","type":"adsb_icao","flight":"TAM8157 ","r":"CC-BGV","t":"B789","desc":"BOEING 787-9 Dreamliner","alt_baro":30850,"alt_geom":31900,"gs":420.7,"ias":314,"tas":496,"mach":0.840,"wd":209,"ws":76,"oat":-44,"tat":-11,"track":199.73,"track_rate":0.00,"roll":0.00,"mag_heading":198.98,"true_heading":201.09,"baro_rate":768,"geom_rate":896,"squawk":"7103","emergency":"none","category":"A5","nav_qnh":1012.8,"nav_altitude_mcp":31008,"nav_heading":198.98,"nav_modes":["autopilot","vnav","lnav","tcas"],"lat":48.741943,"lon":2.486643,"nic":8,"rc":186,"seen_pos":0.019,"version":2,"nic_baro":1,"nac_p":9,"nac_v":1,"sil":3,"sil_type":"perhour","gva":2,"sda":2,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":33747,"seen":0.0,"rssi":-14.3,"dst":8.584,"dir":140.9},
{"hex":"39856b","type":"adsb_icao","flight":"AFR38CD ","r":"F-HBLL","t":"E190","desc":"EMBRAER ERJ-190-100","alt_baro":2600,"alt_geom":3175,"gs":151.6,"ias":152,"tas":158,"mach":0.240,"wd":323,"ws":11,"track":264.70,"track_rate":0.16,"roll":0.88,"mag_heading":266.13,"true_heading":268.26,"baro_rate":2880,"geom_rate":2784,"squawk":"5625","emergency":"none","category":"A3","nav_qnh":1025.6,"nav_altitude_mcp":12000,"nav_altitude_fms":12000,"nav_modes":["autopilot","vnav","tcas"],"lat":48.993903,"lon":2.519483,"nic":8,"rc":186,"seen_pos":0.257,"version":2,"nic_baro":1,"nac_p":10,"nac_v":2,"sil":3,"sil_type":"perhour","gva":2,"sda":2,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":147,"seen":0.0,"rssi":-12.3,"dst":10.784,"dir":38.3},
{"hex":"4d23b8","type":"adsb_icao","flight":"DAH1000 ","r":"9H-MLE","t":"A320","desc":"AIRBUS A-320","alt_baro":11800,"alt_geom":12475,"gs":277.0,"ias":219,"tas":262,"mach":0.412,"wd":211,"ws":31,"oat":-7,"tat":2,"track":89.17,"track_rate":0.03,"roll":0.18,"mag_heading":92.64,"true_heading":94.77,"baro_rate":-1344,"geom_rate":-1312,"squawk":"5562","emergency":"none","category":"A3","nav_qnh":1012.8,"nav_altitude_mcp":7008,"lat":48.917770,"lon":2.592280,"nic":8,"rc":186,"seen_pos":0.149,"version":2,"nic_baro":1,"nac_p":9,"nac_v":1,"sil":3,"sil_type":"perhour","gva":2,"sda":2,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":85202,"seen":0.0,"rssi":-7.6,"dst":10.311,"dir":67.8},
{"hex":"a641f1","type":"adsb_icao","flight":"LXJ502  ","r":"N502FX","t":"CL35","desc":"BOMBARDIER BD-100 Challenger 350","ownOp":"95 MANAGEMENT LLC, HOWARD KEYES, GLOBALFOUNDRIES US INC, SCHRAMM","year":"2022","alt_baro":2000,"alt_geom":2500,"gs":182.5,"ias":182,"tas":192,"mach":0.288,"wd":291,"ws":12,"track":265.60,"track_rate":-0.06,"roll":0.00,"mag_heading":265.08,"true_heading":267.23,"baro_rate":-896,"geom_rate":-1280,"squawk":"1000","category":"A2","nav_qnh":1026.4,"nav_altitude_mcp":2016,"nav_heading":262.97,"lat":48.973932,"lon":2.611132,"nic":8,"rc":186,"seen_pos":0.906,"version":2,"nic_baro":1,"nac_p":11,"nac_v":1,"sil":3,"sil_type":"perhour","gva":2,"sda":2,"alert":0,"spi":0,"mlat":[],"tisb":[],"messages":193804,"seen":0.8,"rssi":-11.0,"dst":12.594,"dir":54.7}
]
,"msg": "No error"
,"now": 1790856796001
,"total": 12
,"ctime": 1790856796001
,"ptime": 0
}
